### ISSUE TITLE
[fixed in develop branch] Redirect after successful login

### ISSUE THREAD

**Issue by OmarElGabry** [panique/huge#754] opened 2015-11-28 17:05 UTC
Hello!,

I noticed a weird behavior, assuming you aren't logged in, and the framework is inside a folder _huge_

If you made a request to `http://localhost/huge/dashboard/index`, 
you will be redirected to `http://localhost/huge/login?redirect=%2Fhuge%2Fdashboard%2Findex`

Then when you try to login successfully, then you will be redirected to `http://localhost/huge/huge/dashboard/index` which will show "404 - Page not found".

Having a quick look into the code, I found that you are using `$_SERVER['REQUEST_URI']` in [Auth](https://github.com/panique/huge/blob/master/application/core/Auth.php#L31), and when you redirect, you use `Config::get('URL')` which result in the above URL.

Is that a potential bug, or I misunderstood something?

Another thing, If you entered wrong email/password, the redirect query parameter in URL will be cleared as implemented in [LoginController](https://github.com/panique/huge/blob/master/application/controller/LoginController.php#L57)

**Comment by panique** [comment] 2015-11-28 20:52
Hey, I don't know exactly where and why the `?redirect=%2Fhuge%2Fdashboard%2Findex` is generated, but it should not contain the subfolder part.

Maybe the redirect feature was added without having subfolders in mind... Sorry I don't know to be honest!

I've never really worked with subfolders as this can be supertricky.

**Comment by panique** [comment] 2015-11-29 20:04
Hi, I'll close this ticket for now as I think it's a problem caused by personal configuration. If you think this might affect other users or is a general bug, please feel free to reopen the ticket!

**Comment by OmarElGabry** [comment] 2015-11-29 20:14
Thanks. Just wanted to give a heads up in case you may consider this as potential bug.

**Comment by panique** [comment] 2016-01-03 17:32
Should be fixed with this pull request here (not mergd now, don't have access to my PHPStorm right now) https://github.com/panique/huge/pull/773

**Closed** 2016-12-04 11:14 UTC
