### ISSUE TITLE
Pressing "Upload image" without an image

### ISSUE THREAD

**Issue by ArneAnka** [panique/huge#655] opened 2015-05-10 14:05 UTC
Gives me this error: 

Warning: getimagesize(): Filename cannot be empty in /Applications/MAMP/htdocs/huge/application/model/AvatarModel.php on line 116

Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/huge/application/model/AvatarModel.php:116) in /Applications/MAMP/htdocs/huge/application/core/Redirect.php on line 25

And then the error is outputted when i click back and click another page.

**Comment by panique** [comment] 2015-05-11 17:30
Any modern browser should not let you press the button without having an image selected. Also, i cannot reproduce this error.

**Comment by ArneAnka** [comment] 2015-05-11 20:39
Added this, not sure if it is a nice way to do it, but solved it.

// "older" browsers (probably php bug or something) need to disable getimagesize error output for redirect
		if (!$image_proportions = @getimagesize($_FILES['avatar_file']['tmp_name'])) {
  			  Session::add('feedback_negative', Text::get('FEEDBACK_AVATAR_IMAGE_UPLOAD_FAILED'));
			return false;
		} 


Im using Safari Version 8.0.4 (10600.4.10.7) with MAMP Version 3.0.7.3 (3.0.7.3) PHP 5.6.2

**Comment by oisian** [comment] 2015-05-12 07:47
I can reproduce using IE11, Chrome or Firefox, Lead's me to believe it's a server configuration issue if you have not modified the code, using @ to suppress and error is the wrong way to go about it,

It will just get forgotten about, if you are just going to ignore it you might as well check if it's set 
with if(issset())

**Comment by panique** [comment] 2015-05-16 00:20
I'll close this as there's no real bug

**Closed by panique** 2015-05-16 00:20 UTC

**Comment by ArneAnka** [comment] 2015-05-18 13:38
application/config/config.development.php line 14, set to 0.

**Comment by panique** [comment] 2015-05-18 15:23
@ArneAnka ??? This does not solve the problem, it just hides the error! Install the application like described in the tutorials and you'll not have any problems.

**Comment by ArneAnka** [comment] 2015-05-18 15:32
Yes i have followed the instructions. I have even looked at the difference between my phpinfo and the demo servers phpinfo to try to locate the "server configuration issue" (@oisian). And my own thoughts is that the error messages (example getimagesize() or missing argument for ProfileController::showProfile() if I'm trying to browse profile/showProfile/ [notice nothing after /, empty argument]) stops the redirect function. 

I can't find anything else. Other ideas is much appreciated!

(and as i said before, i have follow install instructions and i have updated my system
running mac os
mamp pro 3.2.1
apache 
php 5.6.7)

**Comment by panique** [comment] 2015-05-18 16:00
@ArneAnka Sorry, but this is not true, the tutorials doesn't even mention MAMP or Mac OS ! Install this like described in a Ubuntu box and everything will be fine. There's also a one-line auto-installer, so there's absolutly no reason to do any stunts on windows or mac or so. It's really frustrating.
